version: "3.3"
name: "electric_quickstart"
services:
  electric:
    image: electricsql/electric
    environment:
      DATABASE_URL: postgresql://neondb_owner:***@ep-***.us-east-1.aws.neon.tech/neondb?sslmode=require
    ports:
      - "3000:3000"