name: Database Backup and Upload

on:
  # Allows manual triggering from GitHub UI
  workflow_dispatch:
  # Run at 8:33am UTC every day (Will be the middle of the night in the US)
  schedule:
    - cron: "33 8 * * *"

permissions:
  id-token: write
  contents: read

jobs:
  backup-and-upload:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
      - name: Set Timestamp
        run: echo "TIMESTAMP=$(date -u +'%Y-%m-%d-%H-%M-%S')" >> $GITHUB_ENV
      - name: Dump database
        run: npx @neondatabase/pg-import@latest --accept-all true --source "${{ secrets.BACKUP_DB_CONNECTION }}" --backup-file-path "${TIMESTAMP}.sql.gz"
      - name: Configure AWS credentials from Action OIDC
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::AWS_ACCOUNT_ID:role/ROLE_YOU_CREATED_ABOVE
          role-session-name: GitHubActionSession
      - name: Upload backup to S3
        run: |
          YEAR_MONTH=$(date -u +"%Y/%m")
          aws s3 cp "${TIMESTAMP}.sql.gz" s3://${{ secrets.YOUR_S3_BUCKET_NAME }}/database/${YEAR_MONTH}/
